name: Build Armbian
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
env:
  TERM: xterm-256color

jobs:
  package:
  build:
    needs: package
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'armbian/build'
        path: 'build'
        ref: 'v23.05'
        clean: false
    - uses: actions/checkout@v3
      with:
        path: 'Rebuild'

    - name: 'Copy files'
      run: |
        cp -r Rebuild/userpatches build
        cp Rebuild/armbian/recore.csc build/configs/boards/

    - name: Make version number
      run: echo "VERSION=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

    - name: Use tag if tagged
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Create version file
      run: echo "rebuild-${VERSION}" > build/userpatches/overlay/rebuild/rebuild-version

    - name: Run build
      working-directory: ./build
      run: ./compile.sh rebuild

    - name: Delete all old images
      run: rm -f *.img.xz

    - name: Move and rename file
      run: cp build/output/images/Armbian_23.05.0-trunk_Recore_bullseye_legacy_5.15.113_minimal.img.xz ./Rebuild-${VERSION}.img.xz

    - name: Release if tagged
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        allowUpdates: true
        artifacts: Rebuild-v*.img.xz
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
