name: Build Armbian
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
env:
  TERM: xterm-256color

jobs:
  build-mainsail:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        clean: false

    - name: Run build
      run: ./rebuild.sh mainsail

    - name: Release if tagged
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        allowUpdates: true
        artifacts: Rebuild-mainsail-v*.img.xz
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true

  build-barebone:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Run build
      run: ./rebuild.sh barebone

    - name: Release if tagged
      uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        allowUpdates: true
        artifacts: Rebuild-mainsail-v*.img.xz
        token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
